SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CURRENTUSER')
    DROP TABLE CURRENTUSER;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CONCURRENT')
    DROP TABLE CONCURRENT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_USER')
    DROP TABLE TB_USER;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'VERSION')
    DROP TABLE [VERSION];
GO

CREATE TABLE CURRENTUSER(
	strAccountID varchar(50) NOT NULL,
	strCharID varchar(50) NOT NULL,
	nServerNo smallint NOT NULL,
	strServerIP varchar(50) NOT NULL,
	strClientIP varchar(50) NOT NULL
)
GO

CREATE TABLE CONCURRENT(
	[serverid] [tinyint] NOT NULL,
	[zone1_count] [smallint] NOT NULL,
	[zone2_count] [smallint] NOT NULL,
	[zone3_count] [smallint] NOT NULL
) ON [PRIMARY]
GO


CREATE TABLE TB_USER(
	ID int IDENTITY(1,1) NOT NULL,
	strAccountID varchar(21) NOT NULL,
	strPasswd varchar(28) NULL,
	strSealPasswd char(8) NOT NULL DEFAULT 12345678,
	strClientIP char(15) NULL,
	bPremiumType tinyint NOT NULL DEFAULT 0,
	dtPremiumTime datetime DEFAULT GETDATE(),
	sHours smallint NOT NULL DEFAULT 0,
	dtCreateTime datetime DEFAULT GETDATE()
)
GO

CREATE TABLE [VERSION](
	sVersion smallint NOT NULL,
	sHistoryVersion smallint NOT NULL,
	strFilename char(40) NOT NULL
)
GO